package Trilemma;

import Trilemma.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARMOR__INVENTORY.
 */
public class ARMOR_INVENTORY {

    private Long id;
    private Integer number;
    private Integer enhanced_point;
    private java.util.Date update_datetime;
    private Long armor_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ARMOR_INVENTORYDao myDao;

    private ARMOR aRMOR;
    private Long aRMOR__resolvedKey;


    public ARMOR_INVENTORY() {
    }

    public ARMOR_INVENTORY(Long id) {
        this.id = id;
    }

    public ARMOR_INVENTORY(Long id, Integer number, Integer enhanced_point, java.util.Date update_datetime, Long armor_id) {
        this.id = id;
        this.number = number;
        this.enhanced_point = enhanced_point;
        this.update_datetime = update_datetime;
        this.armor_id = armor_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getARMOR_INVENTORYDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getEnhanced_point() {
        return enhanced_point;
    }

    public void setEnhanced_point(Integer enhanced_point) {
        this.enhanced_point = enhanced_point;
    }

    public java.util.Date getUpdate_datetime() {
        return update_datetime;
    }

    public void setUpdate_datetime(java.util.Date update_datetime) {
        this.update_datetime = update_datetime;
    }

    public Long getArmor_id() {
        return armor_id;
    }

    public void setArmor_id(Long armor_id) {
        this.armor_id = armor_id;
    }

    /** To-one relationship, resolved on first access. */
    public ARMOR getARMOR() {
        Long __key = this.armor_id;
        if (aRMOR__resolvedKey == null || !aRMOR__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ARMORDao targetDao = daoSession.getARMORDao();
            ARMOR aRMORNew = targetDao.load(__key);
            synchronized (this) {
                aRMOR = aRMORNew;
            	aRMOR__resolvedKey = __key;
            }
        }
        return aRMOR;
    }

    public void setARMOR(ARMOR aRMOR) {
        synchronized (this) {
            this.aRMOR = aRMOR;
            armor_id = aRMOR == null ? null : aRMOR.getId();
            aRMOR__resolvedKey = armor_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
