package Trilemma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table M__ACTIONSTATUS.
 */
public class M_ACTIONSTATUS {

    private Long id;
    private String action_status;
    private Integer to_attack;
    private Integer to_defense;
    private Integer to_charge;

    public M_ACTIONSTATUS() {
    }

    public M_ACTIONSTATUS(Long id) {
        this.id = id;
    }

    public M_ACTIONSTATUS(Long id, String action_status, Integer to_attack, Integer to_defense, Integer to_charge) {
        this.id = id;
        this.action_status = action_status;
        this.to_attack = to_attack;
        this.to_defense = to_defense;
        this.to_charge = to_charge;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAction_status() {
        return action_status;
    }

    public void setAction_status(String action_status) {
        this.action_status = action_status;
    }

    public Integer getTo_attack() {
        return to_attack;
    }

    public void setTo_attack(Integer to_attack) {
        this.to_attack = to_attack;
    }

    public Integer getTo_defense() {
        return to_defense;
    }

    public void setTo_defense(Integer to_defense) {
        this.to_defense = to_defense;
    }

    public Integer getTo_charge() {
        return to_charge;
    }

    public void setTo_charge(Integer to_charge) {
        this.to_charge = to_charge;
    }

}
