package Trilemma;

import Trilemma.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table M__SKILL__TYPE.
 */
public class M_SKILL_TYPE {

    private Long id;
    private String skill_type_name;
    private Integer skill_type_id;
    private Long action_status_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient M_SKILL_TYPEDao myDao;

    private M_ACTION_STATUS m_ACTION_STATUS;
    private Long m_ACTION_STATUS__resolvedKey;


    public M_SKILL_TYPE() {
    }

    public M_SKILL_TYPE(Long id) {
        this.id = id;
    }

    public M_SKILL_TYPE(Long id, String skill_type_name, Integer skill_type_id, Long action_status_id) {
        this.id = id;
        this.skill_type_name = skill_type_name;
        this.skill_type_id = skill_type_id;
        this.action_status_id = action_status_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getM_SKILL_TYPEDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSkill_type_name() {
        return skill_type_name;
    }

    public void setSkill_type_name(String skill_type_name) {
        this.skill_type_name = skill_type_name;
    }

    public Integer getSkill_type_id() {
        return skill_type_id;
    }

    public void setSkill_type_id(Integer skill_type_id) {
        this.skill_type_id = skill_type_id;
    }

    public Long getAction_status_id() {
        return action_status_id;
    }

    public void setAction_status_id(Long action_status_id) {
        this.action_status_id = action_status_id;
    }

    /** To-one relationship, resolved on first access. */
    public M_ACTION_STATUS getM_ACTION_STATUS() {
        Long __key = this.action_status_id;
        if (m_ACTION_STATUS__resolvedKey == null || !m_ACTION_STATUS__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            M_ACTION_STATUSDao targetDao = daoSession.getM_ACTION_STATUSDao();
            M_ACTION_STATUS m_ACTION_STATUSNew = targetDao.load(__key);
            synchronized (this) {
                m_ACTION_STATUS = m_ACTION_STATUSNew;
            	m_ACTION_STATUS__resolvedKey = __key;
            }
        }
        return m_ACTION_STATUS;
    }

    public void setM_ACTION_STATUS(M_ACTION_STATUS m_ACTION_STATUS) {
        synchronized (this) {
            this.m_ACTION_STATUS = m_ACTION_STATUS;
            action_status_id = m_ACTION_STATUS == null ? null : m_ACTION_STATUS.getId();
            m_ACTION_STATUS__resolvedKey = action_status_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
