package Trilemma;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import Trilemma.PEOPLE;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PEOPLE.
*/
public class PEOPLEDao extends AbstractDao<PEOPLE, Long> {

    public static final String TABLENAME = "PEOPLE";

    /**
     * Properties of entity PEOPLE.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Imgae_no = new Property(1, Integer.class, "imgae_no", false, "IMGAE_NO");
        public final static Property People_name = new Property(2, String.class, "people_name", false, "PEOPLE_NAME");
        public final static Property Serif = new Property(3, String.class, "serif", false, "SERIF");
        public final static Property Town_id = new Property(4, Long.class, "town_id", false, "TOWN_ID");
    };

    private DaoSession daoSession;


    public PEOPLEDao(DaoConfig config) {
        super(config);
    }
    
    public PEOPLEDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PEOPLE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'IMGAE_NO' INTEGER," + // 1: imgae_no
                "'PEOPLE_NAME' TEXT," + // 2: people_name
                "'SERIF' TEXT," + // 3: serif
                "'TOWN_ID' INTEGER);"); // 4: town_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PEOPLE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PEOPLE entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer imgae_no = entity.getImgae_no();
        if (imgae_no != null) {
            stmt.bindLong(2, imgae_no);
        }
 
        String people_name = entity.getPeople_name();
        if (people_name != null) {
            stmt.bindString(3, people_name);
        }
 
        String serif = entity.getSerif();
        if (serif != null) {
            stmt.bindString(4, serif);
        }
 
        Long town_id = entity.getTown_id();
        if (town_id != null) {
            stmt.bindLong(5, town_id);
        }
    }

    @Override
    protected void attachEntity(PEOPLE entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PEOPLE readEntity(Cursor cursor, int offset) {
        PEOPLE entity = new PEOPLE( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // imgae_no
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // people_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // serif
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // town_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PEOPLE entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImgae_no(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPeople_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSerif(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTown_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PEOPLE entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PEOPLE entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTOWNDao().getAllColumns());
            builder.append(" FROM PEOPLE T");
            builder.append(" LEFT JOIN TOWN T0 ON T.'TOWN_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PEOPLE loadCurrentDeep(Cursor cursor, boolean lock) {
        PEOPLE entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TOWN tOWN = loadCurrentOther(daoSession.getTOWNDao(), cursor, offset);
        entity.setTOWN(tOWN);

        return entity;    
    }

    public PEOPLE loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PEOPLE> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PEOPLE> list = new ArrayList<PEOPLE>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PEOPLE> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PEOPLE> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
