package Trilemma;

import Trilemma.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAYER__SKILL.
 */
public class PLAYER_SKILL {

    private Long id;
    private Integer position;
    private Long skill_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient PLAYER_SKILLDao myDao;

    private SKILL sKILL;
    private Long sKILL__resolvedKey;


    public PLAYER_SKILL() {
    }

    public PLAYER_SKILL(Long id) {
        this.id = id;
    }

    public PLAYER_SKILL(Long id, Integer position, Long skill_id) {
        this.id = id;
        this.position = position;
        this.skill_id = skill_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPLAYER_SKILLDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Long getSkill_id() {
        return skill_id;
    }

    public void setSkill_id(Long skill_id) {
        this.skill_id = skill_id;
    }

    /** To-one relationship, resolved on first access. */
    public SKILL getSKILL() {
        Long __key = this.skill_id;
        if (sKILL__resolvedKey == null || !sKILL__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SKILLDao targetDao = daoSession.getSKILLDao();
            SKILL sKILLNew = targetDao.load(__key);
            synchronized (this) {
                sKILL = sKILLNew;
            	sKILL__resolvedKey = __key;
            }
        }
        return sKILL;
    }

    public void setSKILL(SKILL sKILL) {
        synchronized (this) {
            this.sKILL = sKILL;
            skill_id = sKILL == null ? null : sKILL.getId();
            sKILL__resolvedKey = skill_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
