package Trilemma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAYER__STATUS.
 */
public class PLAYER_STATUS {

    private Long id;
    private String status_name;
    private String status_value;

    public PLAYER_STATUS() {
    }

    public PLAYER_STATUS(Long id) {
        this.id = id;
    }

    public PLAYER_STATUS(Long id, String status_name, String status_value) {
        this.id = id;
        this.status_name = status_name;
        this.status_value = status_value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStatus_name() {
        return status_name;
    }

    public void setStatus_name(String status_name) {
        this.status_name = status_name;
    }

    public String getStatus_value() {
        return status_value;
    }

    public void setStatus_value(String status_value) {
        this.status_value = status_value;
    }

}
