package Trilemma;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import Trilemma.PLAYER_SKILL;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLAYER__SKILL.
*/
public class PLAYER_SKILLDao extends AbstractDao<PLAYER_SKILL, Long> {

    public static final String TABLENAME = "PLAYER__SKILL";

    /**
     * Properties of entity PLAYER_SKILL.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Position = new Property(1, Integer.class, "position", false, "POSITION");
        public final static Property Skill_id = new Property(2, Long.class, "skill_id", false, "SKILL_ID");
    };

    private DaoSession daoSession;


    public PLAYER_SKILLDao(DaoConfig config) {
        super(config);
    }
    
    public PLAYER_SKILLDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PLAYER__SKILL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'POSITION' INTEGER," + // 1: position
                "'SKILL_ID' INTEGER);"); // 2: skill_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLAYER__SKILL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PLAYER_SKILL entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer position = entity.getPosition();
        if (position != null) {
            stmt.bindLong(2, position);
        }
 
        Long skill_id = entity.getSkill_id();
        if (skill_id != null) {
            stmt.bindLong(3, skill_id);
        }
    }

    @Override
    protected void attachEntity(PLAYER_SKILL entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PLAYER_SKILL readEntity(Cursor cursor, int offset) {
        PLAYER_SKILL entity = new PLAYER_SKILL( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // position
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // skill_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PLAYER_SKILL entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPosition(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSkill_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PLAYER_SKILL entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PLAYER_SKILL entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSKILLDao().getAllColumns());
            builder.append(" FROM PLAYER__SKILL T");
            builder.append(" LEFT JOIN SKILL T0 ON T.'SKILL_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PLAYER_SKILL loadCurrentDeep(Cursor cursor, boolean lock) {
        PLAYER_SKILL entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SKILL sKILL = loadCurrentOther(daoSession.getSKILLDao(), cursor, offset);
        entity.setSKILL(sKILL);

        return entity;    
    }

    public PLAYER_SKILL loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PLAYER_SKILL> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PLAYER_SKILL> list = new ArrayList<PLAYER_SKILL>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PLAYER_SKILL> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PLAYER_SKILL> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
