package Trilemma;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import Trilemma.SKILL;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SKILL.
*/
public class SKILLDao extends AbstractDao<SKILL, Long> {

    public static final String TABLENAME = "SKILL";

    /**
     * Properties of entity SKILL.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Skill_name = new Property(1, String.class, "skill_name", false, "SKILL_NAME");
        public final static Property Skill_point = new Property(2, Integer.class, "skill_point", false, "SKILL_POINT");
        public final static Property Effect_point = new Property(3, Integer.class, "effect_point", false, "EFFECT_POINT");
        public final static Property Skill_type_id = new Property(4, Long.class, "skill_type_id", false, "SKILL_TYPE_ID");
    };

    private DaoSession daoSession;


    public SKILLDao(DaoConfig config) {
        super(config);
    }
    
    public SKILLDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SKILL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SKILL_NAME' TEXT," + // 1: skill_name
                "'SKILL_POINT' INTEGER," + // 2: skill_point
                "'EFFECT_POINT' INTEGER," + // 3: effect_point
                "'SKILL_TYPE_ID' INTEGER);"); // 4: skill_type_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SKILL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SKILL entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String skill_name = entity.getSkill_name();
        if (skill_name != null) {
            stmt.bindString(2, skill_name);
        }
 
        Integer skill_point = entity.getSkill_point();
        if (skill_point != null) {
            stmt.bindLong(3, skill_point);
        }
 
        Integer effect_point = entity.getEffect_point();
        if (effect_point != null) {
            stmt.bindLong(4, effect_point);
        }
 
        Long skill_type_id = entity.getSkill_type_id();
        if (skill_type_id != null) {
            stmt.bindLong(5, skill_type_id);
        }
    }

    @Override
    protected void attachEntity(SKILL entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SKILL readEntity(Cursor cursor, int offset) {
        SKILL entity = new SKILL( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // skill_name
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // skill_point
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // effect_point
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // skill_type_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SKILL entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSkill_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSkill_point(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setEffect_point(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setSkill_type_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SKILL entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SKILL entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getM_SKILL_TYPEDao().getAllColumns());
            builder.append(" FROM SKILL T");
            builder.append(" LEFT JOIN M__SKILL__TYPE T0 ON T.'SKILL_TYPE_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SKILL loadCurrentDeep(Cursor cursor, boolean lock) {
        SKILL entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        M_SKILL_TYPE m_SKILL_TYPE = loadCurrentOther(daoSession.getM_SKILL_TYPEDao(), cursor, offset);
        entity.setM_SKILL_TYPE(m_SKILL_TYPE);

        return entity;    
    }

    public SKILL loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SKILL> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SKILL> list = new ArrayList<SKILL>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SKILL> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SKILL> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
