package Trilemma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TOWN.
 */
public class TOWN {

    private Long id;
    private String town_name;

    public TOWN() {
    }

    public TOWN(Long id) {
        this.id = id;
    }

    public TOWN(Long id, String town_name) {
        this.id = id;
        this.town_name = town_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTown_name() {
        return town_name;
    }

    public void setTown_name(String town_name) {
        this.town_name = town_name;
    }

}
