package Trilemma;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import Trilemma.WEAPON_INVENTORY;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table WEAPON__INVENTORY.
*/
public class WEAPON_INVENTORYDao extends AbstractDao<WEAPON_INVENTORY, Long> {

    public static final String TABLENAME = "WEAPON__INVENTORY";

    /**
     * Properties of entity WEAPON_INVENTORY.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Number = new Property(1, Integer.class, "number", false, "NUMBER");
        public final static Property Enhanced_point = new Property(2, Integer.class, "enhanced_point", false, "ENHANCED_POINT");
        public final static Property Update_datetime = new Property(3, java.util.Date.class, "update_datetime", false, "UPDATE_DATETIME");
        public final static Property Weapon_id = new Property(4, Long.class, "weapon_id", false, "WEAPON_ID");
    };

    private DaoSession daoSession;


    public WEAPON_INVENTORYDao(DaoConfig config) {
        super(config);
    }
    
    public WEAPON_INVENTORYDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'WEAPON__INVENTORY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NUMBER' INTEGER," + // 1: number
                "'ENHANCED_POINT' INTEGER," + // 2: enhanced_point
                "'UPDATE_DATETIME' INTEGER," + // 3: update_datetime
                "'WEAPON_ID' INTEGER);"); // 4: weapon_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'WEAPON__INVENTORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WEAPON_INVENTORY entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer number = entity.getNumber();
        if (number != null) {
            stmt.bindLong(2, number);
        }
 
        Integer enhanced_point = entity.getEnhanced_point();
        if (enhanced_point != null) {
            stmt.bindLong(3, enhanced_point);
        }
 
        java.util.Date update_datetime = entity.getUpdate_datetime();
        if (update_datetime != null) {
            stmt.bindLong(4, update_datetime.getTime());
        }
 
        Long weapon_id = entity.getWeapon_id();
        if (weapon_id != null) {
            stmt.bindLong(5, weapon_id);
        }
    }

    @Override
    protected void attachEntity(WEAPON_INVENTORY entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WEAPON_INVENTORY readEntity(Cursor cursor, int offset) {
        WEAPON_INVENTORY entity = new WEAPON_INVENTORY( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // number
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // enhanced_point
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // update_datetime
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // weapon_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WEAPON_INVENTORY entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNumber(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setEnhanced_point(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setUpdate_datetime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setWeapon_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WEAPON_INVENTORY entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WEAPON_INVENTORY entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWEAPONDao().getAllColumns());
            builder.append(" FROM WEAPON__INVENTORY T");
            builder.append(" LEFT JOIN WEAPON T0 ON T.'WEAPON_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected WEAPON_INVENTORY loadCurrentDeep(Cursor cursor, boolean lock) {
        WEAPON_INVENTORY entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        WEAPON wEAPON = loadCurrentOther(daoSession.getWEAPONDao(), cursor, offset);
        entity.setWEAPON(wEAPON);

        return entity;    
    }

    public WEAPON_INVENTORY loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<WEAPON_INVENTORY> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<WEAPON_INVENTORY> list = new ArrayList<WEAPON_INVENTORY>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<WEAPON_INVENTORY> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<WEAPON_INVENTORY> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
