package Trilemma;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import Trilemma.ARMOR;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ARMOR.
*/
public class ARMORDao extends AbstractDao<ARMOR, Long> {

    public static final String TABLENAME = "ARMOR";

    /**
     * Properties of entity ARMOR.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Armor_name = new Property(1, String.class, "armor_name", false, "ARMOR_NAME");
        public final static Property Defense_point = new Property(2, Integer.class, "defense_point", false, "DEFENSE_POINT");
    };


    public ARMORDao(DaoConfig config) {
        super(config);
    }
    
    public ARMORDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ARMOR' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ARMOR_NAME' TEXT," + // 1: armor_name
                "'DEFENSE_POINT' INTEGER);"); // 2: defense_point
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ARMOR'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ARMOR entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String armor_name = entity.getArmor_name();
        if (armor_name != null) {
            stmt.bindString(2, armor_name);
        }
 
        Integer defense_point = entity.getDefense_point();
        if (defense_point != null) {
            stmt.bindLong(3, defense_point);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ARMOR readEntity(Cursor cursor, int offset) {
        ARMOR entity = new ARMOR( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // armor_name
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // defense_point
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ARMOR entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setArmor_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDefense_point(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ARMOR entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ARMOR entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
