package Trilemma;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import Trilemma.MONSTER;
import Trilemma.PLAYER;
import Trilemma.EXP_TABLE;
import Trilemma.TOWN;
import Trilemma.DUNGEON;

import Trilemma.MONSTERDao;
import Trilemma.PLAYERDao;
import Trilemma.EXP_TABLEDao;
import Trilemma.TOWNDao;
import Trilemma.DUNGEONDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mONSTERDaoConfig;
    private final DaoConfig pLAYERDaoConfig;
    private final DaoConfig eXP_TABLEDaoConfig;
    private final DaoConfig tOWNDaoConfig;
    private final DaoConfig dUNGEONDaoConfig;

    private final MONSTERDao mONSTERDao;
    private final PLAYERDao pLAYERDao;
    private final EXP_TABLEDao eXP_TABLEDao;
    private final TOWNDao tOWNDao;
    private final DUNGEONDao dUNGEONDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mONSTERDaoConfig = daoConfigMap.get(MONSTERDao.class).clone();
        mONSTERDaoConfig.initIdentityScope(type);

        pLAYERDaoConfig = daoConfigMap.get(PLAYERDao.class).clone();
        pLAYERDaoConfig.initIdentityScope(type);

        eXP_TABLEDaoConfig = daoConfigMap.get(EXP_TABLEDao.class).clone();
        eXP_TABLEDaoConfig.initIdentityScope(type);

        tOWNDaoConfig = daoConfigMap.get(TOWNDao.class).clone();
        tOWNDaoConfig.initIdentityScope(type);

        dUNGEONDaoConfig = daoConfigMap.get(DUNGEONDao.class).clone();
        dUNGEONDaoConfig.initIdentityScope(type);

        mONSTERDao = new MONSTERDao(mONSTERDaoConfig, this);
        pLAYERDao = new PLAYERDao(pLAYERDaoConfig, this);
        eXP_TABLEDao = new EXP_TABLEDao(eXP_TABLEDaoConfig, this);
        tOWNDao = new TOWNDao(tOWNDaoConfig, this);
        dUNGEONDao = new DUNGEONDao(dUNGEONDaoConfig, this);

        registerDao(MONSTER.class, mONSTERDao);
        registerDao(PLAYER.class, pLAYERDao);
        registerDao(EXP_TABLE.class, eXP_TABLEDao);
        registerDao(TOWN.class, tOWNDao);
        registerDao(DUNGEON.class, dUNGEONDao);
    }
    
    public void clear() {
        mONSTERDaoConfig.getIdentityScope().clear();
        pLAYERDaoConfig.getIdentityScope().clear();
        eXP_TABLEDaoConfig.getIdentityScope().clear();
        tOWNDaoConfig.getIdentityScope().clear();
        dUNGEONDaoConfig.getIdentityScope().clear();
    }

    public MONSTERDao getMONSTERDao() {
        return mONSTERDao;
    }

    public PLAYERDao getPLAYERDao() {
        return pLAYERDao;
    }

    public EXP_TABLEDao getEXP_TABLEDao() {
        return eXP_TABLEDao;
    }

    public TOWNDao getTOWNDao() {
        return tOWNDao;
    }

    public DUNGEONDao getDUNGEONDao() {
        return dUNGEONDao;
    }

}
