package Trilemma;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import Trilemma.EXP_TABLE;
import Trilemma.TOWN;
import Trilemma.PEOPLE;
import Trilemma.DUNGEON;
import Trilemma.CHARACTER;
import Trilemma.M_ACTIONSTATUS;
import Trilemma.M_SKILLTYPE;
import Trilemma.SKILL;
import Trilemma.LEARNED_SKILL;
import Trilemma.PLAYER_STATUS;
import Trilemma.STORY_FLAG;

import Trilemma.EXP_TABLEDao;
import Trilemma.TOWNDao;
import Trilemma.PEOPLEDao;
import Trilemma.DUNGEONDao;
import Trilemma.CHARACTERDao;
import Trilemma.M_ACTIONSTATUSDao;
import Trilemma.M_SKILLTYPEDao;
import Trilemma.SKILLDao;
import Trilemma.LEARNED_SKILLDao;
import Trilemma.PLAYER_STATUSDao;
import Trilemma.STORY_FLAGDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eXP_TABLEDaoConfig;
    private final DaoConfig tOWNDaoConfig;
    private final DaoConfig pEOPLEDaoConfig;
    private final DaoConfig dUNGEONDaoConfig;
    private final DaoConfig cHARACTERDaoConfig;
    private final DaoConfig m_ACTIONSTATUSDaoConfig;
    private final DaoConfig m_SKILLTYPEDaoConfig;
    private final DaoConfig sKILLDaoConfig;
    private final DaoConfig lEARNED_SKILLDaoConfig;
    private final DaoConfig pLAYER_STATUSDaoConfig;
    private final DaoConfig sTORY_FLAGDaoConfig;

    private final EXP_TABLEDao eXP_TABLEDao;
    private final TOWNDao tOWNDao;
    private final PEOPLEDao pEOPLEDao;
    private final DUNGEONDao dUNGEONDao;
    private final CHARACTERDao cHARACTERDao;
    private final M_ACTIONSTATUSDao m_ACTIONSTATUSDao;
    private final M_SKILLTYPEDao m_SKILLTYPEDao;
    private final SKILLDao sKILLDao;
    private final LEARNED_SKILLDao lEARNED_SKILLDao;
    private final PLAYER_STATUSDao pLAYER_STATUSDao;
    private final STORY_FLAGDao sTORY_FLAGDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eXP_TABLEDaoConfig = daoConfigMap.get(EXP_TABLEDao.class).clone();
        eXP_TABLEDaoConfig.initIdentityScope(type);

        tOWNDaoConfig = daoConfigMap.get(TOWNDao.class).clone();
        tOWNDaoConfig.initIdentityScope(type);

        pEOPLEDaoConfig = daoConfigMap.get(PEOPLEDao.class).clone();
        pEOPLEDaoConfig.initIdentityScope(type);

        dUNGEONDaoConfig = daoConfigMap.get(DUNGEONDao.class).clone();
        dUNGEONDaoConfig.initIdentityScope(type);

        cHARACTERDaoConfig = daoConfigMap.get(CHARACTERDao.class).clone();
        cHARACTERDaoConfig.initIdentityScope(type);

        m_ACTIONSTATUSDaoConfig = daoConfigMap.get(M_ACTIONSTATUSDao.class).clone();
        m_ACTIONSTATUSDaoConfig.initIdentityScope(type);

        m_SKILLTYPEDaoConfig = daoConfigMap.get(M_SKILLTYPEDao.class).clone();
        m_SKILLTYPEDaoConfig.initIdentityScope(type);

        sKILLDaoConfig = daoConfigMap.get(SKILLDao.class).clone();
        sKILLDaoConfig.initIdentityScope(type);

        lEARNED_SKILLDaoConfig = daoConfigMap.get(LEARNED_SKILLDao.class).clone();
        lEARNED_SKILLDaoConfig.initIdentityScope(type);

        pLAYER_STATUSDaoConfig = daoConfigMap.get(PLAYER_STATUSDao.class).clone();
        pLAYER_STATUSDaoConfig.initIdentityScope(type);

        sTORY_FLAGDaoConfig = daoConfigMap.get(STORY_FLAGDao.class).clone();
        sTORY_FLAGDaoConfig.initIdentityScope(type);

        eXP_TABLEDao = new EXP_TABLEDao(eXP_TABLEDaoConfig, this);
        tOWNDao = new TOWNDao(tOWNDaoConfig, this);
        pEOPLEDao = new PEOPLEDao(pEOPLEDaoConfig, this);
        dUNGEONDao = new DUNGEONDao(dUNGEONDaoConfig, this);
        cHARACTERDao = new CHARACTERDao(cHARACTERDaoConfig, this);
        m_ACTIONSTATUSDao = new M_ACTIONSTATUSDao(m_ACTIONSTATUSDaoConfig, this);
        m_SKILLTYPEDao = new M_SKILLTYPEDao(m_SKILLTYPEDaoConfig, this);
        sKILLDao = new SKILLDao(sKILLDaoConfig, this);
        lEARNED_SKILLDao = new LEARNED_SKILLDao(lEARNED_SKILLDaoConfig, this);
        pLAYER_STATUSDao = new PLAYER_STATUSDao(pLAYER_STATUSDaoConfig, this);
        sTORY_FLAGDao = new STORY_FLAGDao(sTORY_FLAGDaoConfig, this);

        registerDao(EXP_TABLE.class, eXP_TABLEDao);
        registerDao(TOWN.class, tOWNDao);
        registerDao(PEOPLE.class, pEOPLEDao);
        registerDao(DUNGEON.class, dUNGEONDao);
        registerDao(CHARACTER.class, cHARACTERDao);
        registerDao(M_ACTIONSTATUS.class, m_ACTIONSTATUSDao);
        registerDao(M_SKILLTYPE.class, m_SKILLTYPEDao);
        registerDao(SKILL.class, sKILLDao);
        registerDao(LEARNED_SKILL.class, lEARNED_SKILLDao);
        registerDao(PLAYER_STATUS.class, pLAYER_STATUSDao);
        registerDao(STORY_FLAG.class, sTORY_FLAGDao);
    }
    
    public void clear() {
        eXP_TABLEDaoConfig.getIdentityScope().clear();
        tOWNDaoConfig.getIdentityScope().clear();
        pEOPLEDaoConfig.getIdentityScope().clear();
        dUNGEONDaoConfig.getIdentityScope().clear();
        cHARACTERDaoConfig.getIdentityScope().clear();
        m_ACTIONSTATUSDaoConfig.getIdentityScope().clear();
        m_SKILLTYPEDaoConfig.getIdentityScope().clear();
        sKILLDaoConfig.getIdentityScope().clear();
        lEARNED_SKILLDaoConfig.getIdentityScope().clear();
        pLAYER_STATUSDaoConfig.getIdentityScope().clear();
        sTORY_FLAGDaoConfig.getIdentityScope().clear();
    }

    public EXP_TABLEDao getEXP_TABLEDao() {
        return eXP_TABLEDao;
    }

    public TOWNDao getTOWNDao() {
        return tOWNDao;
    }

    public PEOPLEDao getPEOPLEDao() {
        return pEOPLEDao;
    }

    public DUNGEONDao getDUNGEONDao() {
        return dUNGEONDao;
    }

    public CHARACTERDao getCHARACTERDao() {
        return cHARACTERDao;
    }

    public M_ACTIONSTATUSDao getM_ACTIONSTATUSDao() {
        return m_ACTIONSTATUSDao;
    }

    public M_SKILLTYPEDao getM_SKILLTYPEDao() {
        return m_SKILLTYPEDao;
    }

    public SKILLDao getSKILLDao() {
        return sKILLDao;
    }

    public LEARNED_SKILLDao getLEARNED_SKILLDao() {
        return lEARNED_SKILLDao;
    }

    public PLAYER_STATUSDao getPLAYER_STATUSDao() {
        return pLAYER_STATUSDao;
    }

    public STORY_FLAGDao getSTORY_FLAGDao() {
        return sTORY_FLAGDao;
    }

}
