package Trilemma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EXP__TABLE.
 */
public class EXP_TABLE {

    private Long id;
    private Integer level;
    private Integer necessary_exp;
    private java.util.Date last_updatetime;

    public EXP_TABLE() {
    }

    public EXP_TABLE(Long id) {
        this.id = id;
    }

    public EXP_TABLE(Long id, Integer level, Integer necessary_exp, java.util.Date last_updatetime) {
        this.id = id;
        this.level = level;
        this.necessary_exp = necessary_exp;
        this.last_updatetime = last_updatetime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getNecessary_exp() {
        return necessary_exp;
    }

    public void setNecessary_exp(Integer necessary_exp) {
        this.necessary_exp = necessary_exp;
    }

    public java.util.Date getLast_updatetime() {
        return last_updatetime;
    }

    public void setLast_updatetime(java.util.Date last_updatetime) {
        this.last_updatetime = last_updatetime;
    }

}
