package Trilemma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MONSTER.
 */
public class MONSTER {

    private Long id;
    private String monster_name;
    private Integer max_hp;
    private Integer max_skill_point;
    private Integer attack_power;
    private Integer defense_power;
    private Integer profit_gold;
    private Integer profit_exp;
    private java.util.Date last_updatetime;

    public MONSTER() {
    }

    public MONSTER(Long id) {
        this.id = id;
    }

    public MONSTER(Long id, String monster_name, Integer max_hp, Integer max_skill_point, Integer attack_power, Integer defense_power, Integer profit_gold, Integer profit_exp, java.util.Date last_updatetime) {
        this.id = id;
        this.monster_name = monster_name;
        this.max_hp = max_hp;
        this.max_skill_point = max_skill_point;
        this.attack_power = attack_power;
        this.defense_power = defense_power;
        this.profit_gold = profit_gold;
        this.profit_exp = profit_exp;
        this.last_updatetime = last_updatetime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMonster_name() {
        return monster_name;
    }

    public void setMonster_name(String monster_name) {
        this.monster_name = monster_name;
    }

    public Integer getMax_hp() {
        return max_hp;
    }

    public void setMax_hp(Integer max_hp) {
        this.max_hp = max_hp;
    }

    public Integer getMax_skill_point() {
        return max_skill_point;
    }

    public void setMax_skill_point(Integer max_skill_point) {
        this.max_skill_point = max_skill_point;
    }

    public Integer getAttack_power() {
        return attack_power;
    }

    public void setAttack_power(Integer attack_power) {
        this.attack_power = attack_power;
    }

    public Integer getDefense_power() {
        return defense_power;
    }

    public void setDefense_power(Integer defense_power) {
        this.defense_power = defense_power;
    }

    public Integer getProfit_gold() {
        return profit_gold;
    }

    public void setProfit_gold(Integer profit_gold) {
        this.profit_gold = profit_gold;
    }

    public Integer getProfit_exp() {
        return profit_exp;
    }

    public void setProfit_exp(Integer profit_exp) {
        this.profit_exp = profit_exp;
    }

    public java.util.Date getLast_updatetime() {
        return last_updatetime;
    }

    public void setLast_updatetime(java.util.Date last_updatetime) {
        this.last_updatetime = last_updatetime;
    }

}
