package Trilemma;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import Trilemma.MONSTER;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MONSTER.
*/
public class MONSTERDao extends AbstractDao<MONSTER, Long> {

    public static final String TABLENAME = "MONSTER";

    /**
     * Properties of entity MONSTER.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Monster_name = new Property(1, String.class, "monster_name", false, "MONSTER_NAME");
        public final static Property Max_hp = new Property(2, Integer.class, "max_hp", false, "MAX_HP");
        public final static Property Max_skill_point = new Property(3, Integer.class, "max_skill_point", false, "MAX_SKILL_POINT");
        public final static Property Attack_power = new Property(4, Integer.class, "attack_power", false, "ATTACK_POWER");
        public final static Property Defense_power = new Property(5, Integer.class, "defense_power", false, "DEFENSE_POWER");
        public final static Property Profit_gold = new Property(6, Integer.class, "profit_gold", false, "PROFIT_GOLD");
        public final static Property Profit_exp = new Property(7, Integer.class, "profit_exp", false, "PROFIT_EXP");
        public final static Property Last_updatetime = new Property(8, java.util.Date.class, "last_updatetime", false, "LAST_UPDATETIME");
    };


    public MONSTERDao(DaoConfig config) {
        super(config);
    }
    
    public MONSTERDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MONSTER' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "'MONSTER_NAME' TEXT," + // 1: monster_name
                "'MAX_HP' INTEGER," + // 2: max_hp
                "'MAX_SKILL_POINT' INTEGER," + // 3: max_skill_point
                "'ATTACK_POWER' INTEGER," + // 4: attack_power
                "'DEFENSE_POWER' INTEGER," + // 5: defense_power
                "'PROFIT_GOLD' INTEGER," + // 6: profit_gold
                "'PROFIT_EXP' INTEGER," + // 7: profit_exp
                "'LAST_UPDATETIME' INTEGER);"); // 8: last_updatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MONSTER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MONSTER entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String monster_name = entity.getMonster_name();
        if (monster_name != null) {
            stmt.bindString(2, monster_name);
        }
 
        Integer max_hp = entity.getMax_hp();
        if (max_hp != null) {
            stmt.bindLong(3, max_hp);
        }
 
        Integer max_skill_point = entity.getMax_skill_point();
        if (max_skill_point != null) {
            stmt.bindLong(4, max_skill_point);
        }
 
        Integer attack_power = entity.getAttack_power();
        if (attack_power != null) {
            stmt.bindLong(5, attack_power);
        }
 
        Integer defense_power = entity.getDefense_power();
        if (defense_power != null) {
            stmt.bindLong(6, defense_power);
        }
 
        Integer profit_gold = entity.getProfit_gold();
        if (profit_gold != null) {
            stmt.bindLong(7, profit_gold);
        }
 
        Integer profit_exp = entity.getProfit_exp();
        if (profit_exp != null) {
            stmt.bindLong(8, profit_exp);
        }
 
        java.util.Date last_updatetime = entity.getLast_updatetime();
        if (last_updatetime != null) {
            stmt.bindLong(9, last_updatetime.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MONSTER readEntity(Cursor cursor, int offset) {
        MONSTER entity = new MONSTER( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // monster_name
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // max_hp
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // max_skill_point
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // attack_power
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // defense_power
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // profit_gold
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // profit_exp
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // last_updatetime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MONSTER entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMonster_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMax_hp(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setMax_skill_point(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setAttack_power(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setDefense_power(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setProfit_gold(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setProfit_exp(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setLast_updatetime(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MONSTER entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MONSTER entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
