package Trilemma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAYER.
 */
public class PLAYER {

    private Long id;
    private String player_name;
    private Integer level;
    private Integer max_hp;
    private Integer max_skill_point;
    private Integer attack_power;
    private Integer defense_power;
    private Integer current_gold;
    private Integer current_exp;
    private java.util.Date last_updatetime;

    public PLAYER() {
    }

    public PLAYER(Long id) {
        this.id = id;
    }

    public PLAYER(Long id, String player_name, Integer level, Integer max_hp, Integer max_skill_point, Integer attack_power, Integer defense_power, Integer current_gold, Integer current_exp, java.util.Date last_updatetime) {
        this.id = id;
        this.player_name = player_name;
        this.level = level;
        this.max_hp = max_hp;
        this.max_skill_point = max_skill_point;
        this.attack_power = attack_power;
        this.defense_power = defense_power;
        this.current_gold = current_gold;
        this.current_exp = current_exp;
        this.last_updatetime = last_updatetime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPlayer_name() {
        return player_name;
    }

    public void setPlayer_name(String player_name) {
        this.player_name = player_name;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getMax_hp() {
        return max_hp;
    }

    public void setMax_hp(Integer max_hp) {
        this.max_hp = max_hp;
    }

    public Integer getMax_skill_point() {
        return max_skill_point;
    }

    public void setMax_skill_point(Integer max_skill_point) {
        this.max_skill_point = max_skill_point;
    }

    public Integer getAttack_power() {
        return attack_power;
    }

    public void setAttack_power(Integer attack_power) {
        this.attack_power = attack_power;
    }

    public Integer getDefense_power() {
        return defense_power;
    }

    public void setDefense_power(Integer defense_power) {
        this.defense_power = defense_power;
    }

    public Integer getCurrent_gold() {
        return current_gold;
    }

    public void setCurrent_gold(Integer current_gold) {
        this.current_gold = current_gold;
    }

    public Integer getCurrent_exp() {
        return current_exp;
    }

    public void setCurrent_exp(Integer current_exp) {
        this.current_exp = current_exp;
    }

    public java.util.Date getLast_updatetime() {
        return last_updatetime;
    }

    public void setLast_updatetime(java.util.Date last_updatetime) {
        this.last_updatetime = last_updatetime;
    }

}
