package Trilemma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STORY__FLAG.
 */
public class STORY_FLAG {

    private Long id;
    private String flag_name;
    private Boolean story_flag;

    public STORY_FLAG() {
    }

    public STORY_FLAG(Long id) {
        this.id = id;
    }

    public STORY_FLAG(Long id, String flag_name, Boolean story_flag) {
        this.id = id;
        this.flag_name = flag_name;
        this.story_flag = story_flag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFlag_name() {
        return flag_name;
    }

    public void setFlag_name(String flag_name) {
        this.flag_name = flag_name;
    }

    public Boolean getStory_flag() {
        return story_flag;
    }

    public void setStory_flag(Boolean story_flag) {
        this.story_flag = story_flag;
    }

}
