package Trilemma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WEAPON.
 */
public class WEAPON {

    private Long id;
    private String weapon_name;
    private Integer attack_point;

    public WEAPON() {
    }

    public WEAPON(Long id) {
        this.id = id;
    }

    public WEAPON(Long id, String weapon_name, Integer attack_point) {
        this.id = id;
        this.weapon_name = weapon_name;
        this.attack_point = attack_point;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWeapon_name() {
        return weapon_name;
    }

    public void setWeapon_name(String weapon_name) {
        this.weapon_name = weapon_name;
    }

    public Integer getAttack_point() {
        return attack_point;
    }

    public void setAttack_point(Integer attack_point) {
        this.attack_point = attack_point;
    }

}
