package battle.enemy;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import battle.enemy.XXX;

import battle.enemy.XXXDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig xXXDaoConfig;

    private final XXXDao xXXDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        xXXDaoConfig = daoConfigMap.get(XXXDao.class).clone();
        xXXDaoConfig.initIdentityScope(type);

        xXXDao = new XXXDao(xXXDaoConfig, this);

        registerDao(XXX.class, xXXDao);
    }
    
    public void clear() {
        xXXDaoConfig.getIdentityScope().clear();
    }

    public XXXDao getXXXDao() {
        return xXXDao;
    }

}
